# Generated by Django 5.2.17 on 2026-08-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locationData',
            fields=[
                ('site_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(db_column='site_name', max_length=255)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
    ]
